### ISSUE TITLE
[log4j2-appender] Multiple application instances cannot produce to same topic

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar-adapters#15]
**Describe the bug**

Multiple application instances cannot produce to same topic when using the Pulsar Log4j2 appender.
This is due to the fixed producer name set in the log4j2 appender code.

https://github.com/apache/pulsar-adapters/blob/c0bb58d02404f02fd34eaf1c726aa168d90d6e8b/pulsar-log4j2-appender/src/main/java/org/apache/pulsar/log4j2/appender/PulsarManager.java#L116

**To Reproduce**

follow instructions in https://github.com/lhotari/pulsar-log4j2-appender-demo#running-multiple-applications 

**Expected behavior**

Multiple applications should be able to produce log events to the same topic.

**Comment by eolivelli** [comment]
is it possible to not set the producer name ?

**Comment by lhotari** [comment]
> is it possible to not set the producer name ?

No. It's hard coded as you can see in the source code: https://github.com/apache/pulsar-adapters/blob/c0bb58d02404f02fd34eaf1c726aa168d90d6e8b/pulsar-log4j2-appender/src/main/java/org/apache/pulsar/log4j2/appender/PulsarManager.java#L116

**Comment by eolivelli** [comment]
sure.
the patch is easy, is anything stopping us from removing that line or making it configurable ?
