### ISSUE TITLE
pulsar-adapters unsupported consumer replicateSubscriptionState

### ISSUE THREAD

**Issue by slowpao** [apache/pulsar-adapters#51]
**Is your enhancement request related to a problem? Please describe.**
To consume messages across clusters in pulsar, you need to replicate the subscription state

**Describe the solution you'd like**
PulsarConsumerKafkaConfig.getConsumerBuilder() function add replicateSubscriptionState configuration item

**Comment by tisonkun** [comment]
Thanks for your reporting! I file a PR for pass through this option - https://github.com/apache/pulsar-adapters/pull/52

I'll appreciate it if you can test it out.
